# Usamos una imagen base de Nginx para servir el frontend
FROM nginx:alpine

# Copiamos los archivos del frontend en el directorio de Nginx
COPY . /usr/share/nginx/html

# Exponemos el puerto 80 para acceso web
EXPOSE 80
