version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
    command: ["npm", "start"]
  backend_2:
    build: ./BACKEND
    ports:
      - 3001:3001
    command: [ "npm", "run", "dev"]
  frontend:
    build: ./FRONTEND
    ports:
      - "5500:80"
    volumes:
      - ./FRONTEND:/usr/share/nginx/html
    image: nginx:alpine
  
